language: go
go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - master
services:
  - postgresql
  - mysql
before_script:
  - psql -c 'create database gomigrate;' -U postgres
  - mysql -uroot -e "CREATE USER 'gomigrate'@'localhost' IDENTIFIED BY 'password';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'gomigrate'@'localhost';"
  - mysql -uroot -e "CREATE DATABASE gomigrate;"
script:
  - DB=pg go test
  - DB=sqlite3 go test
