language: go
go:
  - "1.8"
  - "1.10.x"
  - master
services:
  - postgresql
  - mysql
before_script:
  - psql -c 'create database gomigrate;' -U postgres
  - mysql -uroot -e "CREATE USER 'gomigrate'@'localhost' IDENTIFIED BY 'password';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'gomigrate'@'localhost';"
  - mysql -uroot -e "CREATE DATABASE gomigrate;"
  - go get github.com/lib/pq
  - go get github.com/go-sql-driver/mysql
  - go get github.com/mattn/go-sqlite3
  - go get github.com/denisenkom/go-mssqldb
script:
  - DB=pg go test
  - DB=mysql go test
  - DB=sqlite3 go test
